services:
  loki:
    image: grafana/loki:2.9.4
    container_name: monitoring-loki-1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    container_name: monitoring-promtail-1
    volumes:
      - ../logs:/logs
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: monitoring-grafana-1
    ports:
      - "3001:3000"
    depends_on:
      - loki
    restart: unless-stopped
